version = "1.0.2"
dependencies = ["libgtk-4-dev", "meson"]
arch = "amd64"

[source.git-clone]
url = "https://github.com/iliabylich/gaskpass.git"
branch-or-tag = "v1.0.2"

[debian]
changelog = true
compat = 10

[debian.control]
description = "a micro tool written in GTK4 to be used as SUDO_ASKPASS"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_configure = ["dh_auto_configure -- --buildtype=release"]
