version = "0-0-stamp"
dependencies = ["nodejs", "npm", "just", "musl", "musl-dev"]
arch = "amd64"

[source.git-clone]
url = "https://github.com/iliabylich/hn-parser.git"
branch-or-tag = "master"

[debian]
changelog = true
compat = 10

[debian.control]
description = "HN parser"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_build = [
    "npm install",
    "just tailwind-build",
    "rustup target add x86_64-unknown-linux-musl",
    "cargo build --release --target=x86_64-unknown-linux-musl",
]
override_dh_auto_install = [
    "install -Dm0755 target/x86_64-unknown-linux-musl/release/hnparser debian/hnparser/usr/bin/hnparser",
    "install -Dm0644 debian/hnparser.service debian/hnparser/usr/lib/systemd/system/hnparser.service",
]
