version = "0-0-stamp"
dependencies = []
arch = "amd64"

source = "none"

[debian]
changelog = true
compat = 10

[debian.control]
description = "Meta-package that depends on all packages that I use"
dependencies = [
    # Gnome
    "nautilus",
    "gnome-system-monitor",
    "tuigreet",
    "greetd",

    # UI apps
    # "flatpak",
    "localsend",
    # "blanket",
    # "mpv",
    # "transmission-gtk",
    # "amberol",
    "loupe",
    # "gedit",
    # "baobab",
    "d-spy",
    # "file-roller",
    # "obfuscate",
    # "zenity",
    # "ghostty",
    # "spot",
    "wezterm",

    # Dev tools
    "gcc",
    "build-essential",
    "cmake",
    "meson",
    "ragel",
    "valgrind",
    "google-perftools",
    "bison",
    "strace",
    "rustfilt",
    "sqlite3",
    "gh",
    "pkg-config",
    "make",
    "git",
    "llvm",
    "clang",
    "lld",
    "clangd",
    "linux-perf",
    "gdb",
    "sassc",
    "autoconf",
    "automake",
    "xxd",
    "clang-tidy",
    "blueprint-compiler",
    "podman",
    "musl",

    # CLI
    "hugo",
    "jq",
    "nmap",
    "yq",
    "pipx",
    "gnupg2",
    "just",
    "git-delta",
    "bat",
    "fastfetch",
    "htop",
    "nano",
    "tree",
    "ffmpeg",
    "libnotify-bin",
    "stow",
    "traceroute",
    "wget",
    "curl",
    "fx",
    "starship",
    "du-dust",
    "gaskpass",
    "xremap",
    "pipewire-dbus",
    "apache2-utils",
    "wireplumber",
    "bash-completion",
    "file",
    "less",
    "sudo",
    "fakeroot",
    "openssh-client",
    "zip",
    "unzip",
    "pkexec",
    "logrotate",
    "lsd",
    "iotop",
    "powertop",
    "shellcheck",
    "iputils-ping",
    "x11-utils",
    "parallel",

    # Libs
    "libjemalloc-dev",
    "libgtk-4-dev",
    "libgtk4-layer-shell-dev",
    "libvte-2.91-gtk4-dev",
    "libpipewire-0.3-dev",
    "libdbus-1-dev",
    "libssl-dev",
    "libclang-rt-dev",
    "musl-dev",

    # Debian
    "apt-file",
    "make-btrfs-snapshot",
    "xwayland",
    "lsb-release",
    "network-manager",
    "iwd",
    "discover",
    "ncurses-term",
    "xdg-utils",
    "wireless-tools",
    "fonts-inter-variable",
    "fonts-inter-variable-nerd",
    "fonts-adwaita-mono-nerd",

    # Hyprland
    "hyprland",
    "hyprlock",
    "swaybg",
    "dunst",
    "wl-clipboard",
    "wf-recorder",
    "slurp",
    "grim",
    "satty",
    "cliphist",
    "layer-shell",
    "pavucontrol",
    "swayosd",
    "hyprsunset",
    "hyprland-qtutils",
    "hyprsysteminfo",
    "hyprpolkitagent",
    "hyprland-qt-support",
    "xdg-desktop-portal-hyprland",
    "unsplash-wallpaper",
    "matugen",
    "hyprspace",
    "bluez",
    "fuzzel",
    "iwmenu",
    "bzmenu",
]

[debian.rules]
"%" = ["dh $@"]
