version = "0-0-stamp"
dependencies = ["musl", "musl-dev"]
arch = "amd64"

[source.git-clone]
url = "https://github.com/iliabylich/myip.git"
branch-or-tag = "master"

[debian]
changelog = true
compat = 10

[debian.control]
description = "a tiny service that returns client's IP"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_build = [
    "rustup target add x86_64-unknown-linux-musl",
    "cargo build --release --target=x86_64-unknown-linux-musl",
]
override_dh_auto_install = [
    "install -Dm0755 target/x86_64-unknown-linux-musl/release/myip debian/myip/usr/bin/myip",
    "install -Dm0644 debian/myip.service debian/myip/usr/lib/systemd/system/myip.service",
]
