version = "3.0.3"
dependencies = ["libpipewire-0.3-dev", "libclang1", "clang", "meson"]
arch = "amd64"

[source.git-clone]
url = "https://github.com/iliabylich/pipewire-dbus.git"
branch-or-tag = "v3.0.3"

[debian]
changelog = true
compat = 10

[debian.control]
description = "A daemon service that triggers Pipewire volume events over DBus"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_configure = ["dh_auto_configure -- --buildtype=release"]
