version = "0.14.1"
dependencies = []
arch = "amd64"

[source.git-clone]
url = "https://github.com/xremap/xremap.git"
branch-or-tag = "v0.14.1"

[debian]
changelog = true
compat = 10

[debian.control]
description = "Key remapper for X11 and Wayland"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_build = [
    "CARGO_TERM_COLOR=always cargo build --release --features hypr",
]
override_dh_auto_install = [
    "install -Dm0755 target/release/xremap debian/xremap/usr/bin/xremap",
]
