version = "0.7.0"
dependencies = ["meson"]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/hyprland-protocols.git"
branch-or-tag = "v0.7.0"

[debian]
changelog = true
compat = 10

[debian.control]
description = "Wayland protocol extensions for Hyprland"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_configure = ["meson setup build"]
override_dh_auto_build = ["@true"]
override_dh_auto_install = [
    "meson install -C build --destdir=$$PWD/debian/hyprland-protocols",
]
override_dh_usrlocal = ["@true"]
