version = { specific = "0.8.3" }
dependencies = ["libpixman-1-dev"]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/hyprutils.git"
branch_or_tag = "v0.8.3"

[debian]
changelog = true
compat = 10

[debian.control]
description = "Hyprland utilities library used across the ecosystem"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_configure = [
    "cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build",
]
override_dh_auto_build = [
    "cmake --build ./build --config Release --target all -j`nproc`",
]
override_dh_auto_install = [
    "cmake --install build --prefix debian/hyprutils/usr",
]
