version = "0.4.5-1"
dependencies = ["libpugixml-dev"]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/hyprwayland-scanner.git"
branch-or-tag = "v0.4.5"

[debian]
changelog = true
compat = 10

[debian.control]
description = "A Hyprland implementation of wayland-scanner, in and for C++."
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_configure = ["cmake -DCMAKE_INSTALL_PREFIX=/usr -B build"]
override_dh_auto_build = ["cmake --build build -j `nproc`"]
override_dh_auto_install = [
    "cmake --install build --prefix debian/hyprwayland-scanner/usr",
]
