version = { specific = "0.1.12-1" }
dependencies = [
    "/shared/deb-latest/hyprutils.deb",
    "/shared/deb-latest/hyprlang.deb",

    "libzip-dev",
    "libcairo2-dev",
    "librsvg2-dev",
    "libtomlplusplus-dev",
]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/hyprcursor.git"
branch_or_tag = "v0.1.12"

[debian]
changelog = true
compat = 10

[debian.control]
description = "The hyprland cursor format, library and utilities."
dependencies = ["${shlibs:Depends}"]

[debian.rules]
override_dh_auto_configure = ["echo skip"]
override_dh_auto_build = [
    "cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build",
    "cmake --build ./build --config Release --target all -j`nproc`",
]
override_dh_auto_install = [
    "cmake --install build --prefix debian/hyprcursor/usr",
]
