version = "0.6.4-1"
dependencies = ["/shared/deb-latest/hyprutils.deb"]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/hyprlang.git"
branch-or-tag = "v0.6.4"

[debian]
changelog = true
compat = 10

[debian.control]
description = "The official implementation library for the hypr config language."
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_configure = [
    "cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build",
]
override_dh_auto_build = [
    "cmake --build ./build --config Release --target hyprlang -j`nproc`",
]
override_dh_auto_install = [
    "cmake --install build --prefix debian/hyprlang/usr",
]
