version = { specific = "0.50.0" }
dependencies = [
    "/shared/deb-latest/aquamarine.deb",
    "/shared/deb-latest/hyprlang.deb",
    "/shared/deb-latest/hyprcursor.deb",
    "/shared/deb-latest/hyprutils.deb",
    "/shared/deb-latest/hyprgraphics.deb",
    "/shared/deb-latest/hyprland.deb",
    "libpixman-1-dev",
    "libdrm-dev",
    "libpango1.0-dev",
    "libinput-dev",
    "libudev-dev",
    "libwayland-dev",
    "libxkbcommon-dev",
]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/hyprland-plugins.git"
branch_or_tag = "v0.50.0"

[debian]
changelog = true
compat = 10

[debian.control]
description = "Official plugins for Hyprland"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_configure = ["@true"]
override_dh_auto_build = [
    "cd borders-plus-plus && make",
    "cd hyprbars && make",
    "cd hyprexpo && make",
    "cd hyprfocus && make",
]
override_dh_auto_install = [
    "install -Dm0644 borders-plus-plus/borders-plus-plus.so debian/hyprland-plugins/usr/lib/x86_64-linux-gnu/hyprland-plugins/borders-plus-plus.so",
    "install -Dm0644 hyprbars/hyprbars.so debian/hyprland-plugins/usr/lib/x86_64-linux-gnu/hyprland-plugins/hyprbars.so",
    "install -Dm0644 hyprexpo/hyprexpo.so debian/hyprland-plugins/usr/lib/x86_64-linux-gnu/hyprland-plugins/hyprexpo.so",
    "install -Dm0644 hyprfocus/hyprfocus.so debian/hyprland-plugins/usr/lib/x86_64-linux-gnu/hyprland-plugins/hyprfocus.so",
]
