version = "0.1.5-1"
dependencies = [
    "/shared/deb-latest/hyprutils.deb",

    "qt6-base-dev",
    "qt6-declarative-dev",
    "qt6-declarative-private-dev",

    "qt6-wayland-dev",
    "qt6-wayland-private-dev",
    "qml6-module-qtwayland-compositor",

    "qml6-module-qtcore",
    "qml6-module-qtqml",
    "qml6-module-qtqml-workerscript",
    "qml6-module-qtqml-models",
    "qml6-module-qtquick",
    "qml6-module-qtquick-controls",
    "qml6-module-qtquick-layouts",
    "qml6-module-qtquick-templates",
    "qml6-module-qtquick-window",
    "libqt6quick6",
]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/hyprland-qtutils.git"
branch-or-tag = "v0.1.5"

[debian]
changelog = true
compat = 10

[debian.control]
description = "Hyprland QT/qml utility apps"
dependencies = [
    "${shlibs:Depends}",
    "qml6-module-qtcore",
    "qml6-module-qtqml-workerscript",
    "qml6-module-qtqml-models",
    "qml6-module-qtquick",
    "qml6-module-qtquick-controls",
    "qml6-module-qtquick-layouts",
    "qml6-module-qtquick-templates",
    "qml6-module-qtquick-window",
]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_configure = [
    "cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build",
]
override_dh_auto_build = [
    "cmake --build ./build --config Release --target all -j`nproc`",
]
override_dh_auto_install = [
    "cmake --install build --prefix debian/hyprland-qtutils/usr",
]
