version = "20260219"
dependencies = ["wget"]
arch = "all"

source = "none"

[debian]
changelog = true
compat = 10

[debian.control]
description = "Apple Color Emoji font"
dependencies = []

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_build = [
    "wget -q https://github.com/samuelngs/apple-emoji-ttf/releases/download/macos-26-20260219-2aa12422/AppleColorEmoji-Linux.ttf -O AppleColorEmoji.ttf",
]
override_dh_auto_install = [
    "mkdir -p debian/fonts-apple-color-emoji/usr/share/fonts/apple-color-emoji",
    "install -m644 *.ttf debian/fonts-apple-color-emoji/usr/share/fonts/apple-color-emoji/",
]
